from engine.order_book import OrderBook


class MatchingEngine:
    """
    Coordinates order processing, records completed trades,
    and settles trades between traders.
    """

    def __init__(self):

        self.order_book = OrderBook()

        # Stores completed trades
        self.trade_history = []

        # trader_id -> Trader object
        self.traders = {}



    def register_trader(self, trader):
        """
        Adds a trader to the exchange.
        """

        self.traders[trader.trader_id] = trader



    def submit_order(self, order):
        """
        Submits an order to the order book.

        Returns:
            list[Trade]: Trades generated by the order.
        """


        # Update order book time
        self.order_book.current_step = order.timestamp


        # Remove any orders that have expired and give their
        # traders back the cash/shares that were reserved for them.
        expired_orders = self.order_book.remove_expired_orders()

        for expired_order in expired_orders:
            self._release_reservation(expired_order)


        trades = self.order_book.process_order(order)


        for trade in trades:

            buyer_id = trade.buy_order.trader_id
            seller_id = trade.sell_order.trader_id


            if (
                buyer_id in self.traders
                and seller_id in self.traders
            ):

                self.settle_trade(trade)


        self.trade_history.extend(
            trades
        )


        return trades



    def cancel_order(self, order_id):
        """
        Cancels an active order and releases any cash/shares
        that were reserved for it.
        """

        order = self.order_book.orders.get(order_id)

        if order is None:
            return False


        cancelled = self.order_book.cancel_order(order_id)

        if cancelled:
            self._release_reservation(order)


        return cancelled



    def _release_reservation(self, order):
        """
        Releases whatever cash/shares were reserved for the
        unfilled portion of an order that was removed from the
        book without being fully matched (expired or cancelled).
        """

        trader = self.traders.get(order.trader_id)

        if trader is None:
            return


        if order.side == "BUY":

            trader.portfolio.release_cash(
                order.remaining_quantity * order.price
            )

        else:

            trader.portfolio.release_shares(
                order.symbol,
                order.remaining_quantity
            )



    def settle_trade(self, trade):
        """
        Updates buyer and seller portfolios after a trade.
        """

        buyer = self.traders[
            trade.buy_order.trader_id
        ]

        seller = self.traders[
            trade.sell_order.trader_id
        ]


        #
        # Release reservations
        #
        # Release based on each order's *original* submitted price,
        # since that is the amount that was actually reserved at
        # submission time. The trade may execute at a different
        # (better) price than the order's own limit price, and using
        # trade.price here would leave a small amount of cash/shares
        # permanently stuck in "reserved" limbo.
        #

        buyer.portfolio.release_cash(
            trade.quantity * trade.buy_order.price
        )

        seller.portfolio.release_shares(
            trade.sell_order.symbol,
            trade.quantity
        )


        #
        # Execute the trade
        #

        buyer.portfolio.buy(
            trade.buy_order.symbol,
            trade.quantity,
            trade.price
        )

        seller.portfolio.sell(
            trade.sell_order.symbol,
            trade.quantity,
            trade.price
        )



    def get_trade_history(self):
        """
        Returns all trades executed so far.
        """

        return self.trade_history



    def get_best_bid(self):
        return self.order_book.get_best_bid()



    def get_best_ask(self):
        return self.order_book.get_best_ask()



    def get_order_book_depth(self):
        return self.order_book.get_order_book_depth()
