from engine.order_book import OrderBook


class MatchingEngine:
    """
    Coordinates order processing, records completed trades,
    and settles trades between traders.

    Owns one OrderBook per symbol, so different stocks never match
    against each other.
    """

    def __init__(self):

        # Symbol -> OrderBook
        self.order_books = {}

        # Stores completed trades (across all symbols)
        self.trade_history = []

        # trader_id -> Trader object
        self.traders = {}



    def _get_order_book(self, symbol):
        """
        Returns the OrderBook for a symbol, creating an empty one the
        first time that symbol is seen.
        """

        if symbol not in self.order_books:

            self.order_books[symbol] = OrderBook()


        return self.order_books[symbol]



    def register_trader(self, trader):
        """
        Adds a trader to the exchange.
        """

        self.traders[trader.trader_id] = trader



    def submit_order(self, order):
        """
        Submits an order to the appropriate symbol's order book.

        Returns:
            list[Trade]: Trades generated by the order.
        """

        book = self._get_order_book(order.symbol)


        # Update order book time
        book.current_step = order.timestamp


        # Remove any orders that have expired and give their
        # traders back the cash/shares that were reserved for them.
        expired_orders = book.remove_expired_orders()

        for expired_order in expired_orders:
            self._release_reservation(expired_order)


        trades = book.process_order(order)


        for trade in trades:

            buyer_id = trade.buy_order.trader_id
            seller_id = trade.sell_order.trader_id


            if (
                buyer_id in self.traders
                and seller_id in self.traders
            ):

                self.settle_trade(trade)


        self.trade_history.extend(
            trades
        )


        # MARKET orders never rest in the book. If one couldn't be
        # fully filled right now, whatever cash/shares were reserved
        # for the unfilled remainder need to be released immediately,
        # since there's no resting order left to eventually fill it.
        
        if order.order_type == "MARKET" and not order.is_filled():

            self._release_reservation(order)


        return trades



    def cancel_order(self, order_id):
        """
        Cancels an active order (searching across all symbols) and
        releases any cash/shares that were reserved for it.
        """

        for book in self.order_books.values():

            if order_id in book.orders:

                order = book.orders[order_id]

                cancelled = book.cancel_order(order_id)

                if cancelled:
                    self._release_reservation(order)

                return cancelled


        return False



    def _release_reservation(self, order):
        """
        Releases whatever cash/shares were reserved for the
        unfilled portion of an order that was removed from the
        book without being fully matched (expired or cancelled).
        """

        trader = self.traders.get(order.trader_id)

        if trader is None:
            return


        if order.side == "BUY":

            trader.portfolio.release_cash(
                order.remaining_quantity * order.reservation_price
            )

        else:

            trader.portfolio.release_shares(
                order.symbol,
                order.remaining_quantity
            )



    def settle_trade(self, trade):
        """
        Updates buyer and seller portfolios after a trade.
        """

        buyer = self.traders[
            trade.buy_order.trader_id
        ]

        seller = self.traders[
            trade.sell_order.trader_id
        ]


        #
        # Release reservations
        #
        # Release based on each order's *original* reservation amount,
        # since that is what was actually locked up at submission time.
        # The trade may execute at a different (better) price than the
        # order's own price, and using trade.price here would leave a
        # small amount of cash/shares permanently stuck in "reserved"
        # limbo.
        #

        buyer.portfolio.release_cash(
            trade.quantity * trade.buy_order.reservation_price
        )

        seller.portfolio.release_shares(
            trade.sell_order.symbol,
            trade.quantity
        )


        #
        # Execute the trade
        #

        buyer.portfolio.buy(
            trade.buy_order.symbol,
            trade.quantity,
            trade.price
        )

        seller.portfolio.sell(
            trade.sell_order.symbol,
            trade.quantity,
            trade.price
        )



    def get_trade_history(self):
        """
        Returns all trades executed so far, across all symbols.
        """

        return self.trade_history



    def get_best_bid(self, symbol="AAPL"):
        return self._get_order_book(symbol).get_best_bid()



    def get_best_ask(self, symbol="AAPL"):
        return self._get_order_book(symbol).get_best_ask()



    def get_order_book_depth(self, symbol="AAPL"):
        return self._get_order_book(symbol).get_order_book_depth()



    def estimate_market_fill(self, symbol, side, quantity):
        return self._get_order_book(symbol).estimate_market_fill(
            side,
            quantity
        )
